### ISSUE TITLE
Steps to run and upload in Readme

### ISSUE THREAD

**Issue by fizerkhan** [Syncano/syncano.com#317]
First of all, Thanks for making your website code as an open source. 

It will be great if you add the steps about how to run and how to upload the build to S3. 
For me, it gets failed in getting billing and tweets JSON. If you mentioned about it in the doc, it will be nicer.

**Comment by wpasinski** [comment]
Hi @fizerkhan,

A few days ago we updated our public config and README file. Please pull latest changes and then you should be able to run the website with no problems.

https://github.com/Syncano/syncano.com#how-to-run

**Comment by fizerkhan** [comment]
@wpasinski  Thanks for update.
